### ISSUE TITLE
Alternatives to GPL?

### ISSUE THREAD

**Issue by franslundberg** [WhisperSystems/curve25519-java#15]
Thank you for the Java code for curve25519.

We (ASSA ABLOY AB) has released the Salt Channel protocol based in the TweetNaCl library as open source (https://github.com/assaabloy-ppi/salt-channel/). We would like to release it with the MIT license, but cannot since we depend on some GPL code for the TweetNaCl code.

We would love to use this repo (WhisperSystems/curve25519-java), but the GPL license is problematic. 

Any possibility you would release this low-level library with the MIT licence (for example)? Or to the public domain? In the spirit of Bernstein's original public domain implementation.

**Comment by moxie0** [comment]
Hey @franslundberg we don't use issue trackers on github for questions or discussion, only for tracking bugs and issues. The mailing list is a more appopriate forum for questions and discussion, thanks.
