### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by varunagarwal315** [WhisperSystems/curve25519-java#16]
I understood how to generate and extract the public and private keys generated. However not sure how to actually use them to encrypt a message. I am using this lib for my backend https://github.com/dchest/tweetnacl-js which has a method that encrypts the message using my private key and you public key.

Is this feature currently not supported. Is there a way I can work around it ? Please help

**Comment by moxie0** [comment]
Hey @varunagarwal315 we don't use github for q&a or discussion, please see the online community forums. Sounds like you probably shouldn't be using this library directly, I recommend looking at libsignal-protocol-java instead.
