### ISSUE TITLE
Alternate license or library exception?

### ISSUE THREAD

**Issue by damccull** [WhisperSystems/curve25519-java#23]
Hello,

I'm interested in using your fantastic Curve25519 library, but I differ in opinion with the FSF that my program should be considered a derivative work of your library and therefore also subject to GPLv3. As your current license is a verbatim copy of GPLv3 with no exceptions and I can't find any exceptions in your repository, I am unable to bring myself to use your library in my project.

Would you consider releasing this under an alternative license as well, or perhaps including an exception to the GPLv3 that allows programs using your code strictly as a library without modification to be exempt from also having to license under GPLv3?

I code in C#, but your library has been ported to C# before, also under the terms of GPLv3, as is required. I would like to either port it again under an alternate license, or, more preferably, ask someone who's also ported it to update their license with an exception or alternate license if I can convince you to do it first.

Thank you for your time.

**Comment by moxie0** [comment]
Thanks @damccull but we don't use GH issues for Q/A or discussion.
