### ISSUE TITLE
ed_y not being used in curve25519_keygen

### ISSUE THREAD

**Issue by kushti** [WhisperSystems/curve25519-java#6]
In curve_sigs.curve25519_keygen variable ed_y is never used. Seems like a red flag to me. Please re-check the method code against a reference implementation.

**Comment by benjyz** [comment]
refers to this line https://github.com/WhisperSystems/curve25519-java/blob/master/common/src/main/java/org/whispersystems/curve25519/java/curve_sigs.java#L9

**Comment by benjyz** [comment]
fixed here
https://github.com/WhisperSystems/curve25519-java/pull/8
